repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        language: system
        entry: rustfmt
        files: .*\.rs$
